# Generated by Django 5.2.17 on 2026-08-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('n', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FREE', 'FREE'), ('TAKEN', 'TAKEN')], default='FREE', max_length=8)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'n'], name='provisionin_status_af4863_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PROVISIONING', 'PROVISIONING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('DELETED', 'DELETED')], default='PROVISIONING', max_length=16)),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vms', to='provisioning.slot')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='provisionin_status_0f4294_idx')],
            },
        ),
    ]
