# Generated by Django 5.2.17 on 2026-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
