# Generated by Django 5.2.17 on 2026-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_vm_claimed_at_vm_claimed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='status',
            field=models.CharField(choices=[('PROVISIONING', 'PROVISIONING'), ('ACTIVE', 'ACTIVE'), ('DELETING', 'DELETING'), ('FAILED', 'FAILED'), ('DELETED', 'DELETED')], default='PROVISIONING', max_length=16),
        ),
    ]
