# Generated by Django 5.2.17 on 2026-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_alter_vm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='student_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
